version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: test_management
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w#E$R
      MYSQL_DATABASE: test_management
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 1q2w#E$R
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --skip-host-cache
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: test_platform_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:1q2w#E$R@mysql:3306/test_management
      - SECRET_KEY=your-secret-key-here
      - FLASK_ENV=development
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app

volumes:
  mysql_data:
