services:
  - type: web
    name: test-platform-backend
    env: python
    buildCommand: cd integrated-test-platform/backend && pip install -r requirements.txt
    startCommand: cd integrated-test-platform/backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_jAtyhE2HW3pY@ep-hidden-paper-a1iuh28r-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app,http://localhost:3000 