"""Add AutomationTestResults table

Revision ID: 07409f8916ea
Revises: 3a94b32686ae
Create Date: 2025-08-05 13:55:40.059105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07409f8916ea'
down_revision = '3a94b32686ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AutomationTestResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_test_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_start', sa.DateTime(), nullable=True),
    sa.Column('execution_end', sa.DateTime(), nullable=True),
    sa.Column('execution_duration', sa.Float(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['automation_test_id'], ['AutomationTests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AutomationTestResults')
    # ### end Alembic commands ###
