"""Add Guest role support

Revision ID: 69da2698ad3e
Revises: 07409f8916ea
Create Date: 2025-08-06 08:50:57.946161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69da2698ad3e'
down_revision = '07409f8916ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
